In [1]:
import tensorflow as tf
"""
Everything in TensorFlow is based on Tensor operations.
Tensors are (kind of) like np.arrays.
All tensors are immutable: you can never update the contents of a
tensor, only create a new one.

 - nd-arrays (1d, 2d, or even 3d and higher)
 - GPU support
 - Computational graph / Track gradients / Backpropagation
 - Immutable!
"""

Init Plugin
Init Graph Optimizer
Init Kernel


'\nEverything in TensorFlow is based on Tensor operations.\nTensors are (kind of) like np.arrays.\nAll tensors are immutable: you can never update the contents of a\ntensor, only create a new one.\n\n - nd-arrays (1d, 2d, or even 3d and higher)\n - GPU support\n - Computational graph / Track gradients / Backpropagation\n - Immutable!\n'

# 1. create tensors
# scalar, rank-0 tensor

In [2]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
x

Metal device set to: Apple M1


2022-05-08 11:49:33.223177: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-08 11:49:33.223509: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [8]:
x = tf.constant(4, shape=(1,))
x

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>

In [10]:
x = tf.zeros((3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
x = tf.random.uniform((3, 3), minval=0, maxval=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.38862407, 0.10394657, 0.99629986],
       [0.10825944, 0.00161183, 0.5364164 ],
       [0.45114863, 0.4766605 , 0.95294607]], dtype=float32)>

In [14]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.92317027,  0.5074085 ,  1.0412927 ],
       [ 0.6573978 , -1.341036  ,  1.4886831 ],
       [ 0.7897051 ,  0.09944075, -0.9366341 ]], dtype=float32)>